travis:
  secure:
    BINSTAR_TOKEN: fVXRij4JWV/RxKPMxKCQTkR6SdaGZqWQOW9uY+JPcX2oKaZ3R47c/ClsL7zuQbMPyN7r4cjLDsxu5pV5Rb7NStR3MI/h7v1uophj/yFetysOkT8PJBo1rdf+6jCBX5Tbu0lCvm5YCNdYA7w8Pb5Wo9J3QRMOKrgKZd21ECXIVbyrZVV0XeFOT9OnKo1E+bKjHVtoIq/85IVy360kuzSuslP0qUFOzVSgKlO6Txs7AAUKrgG6Ry+9bGjUK8jdowTWC0NUX1PqSgFU97sTpA8TSQxbT6BoKmOIFmaiFk6TM/NnJu751PLi7dPbmpmisY+GwHPeKUXD07BltS8mX5MLOaQhRGuuLFFGBnXoEnagKNTfPCe+DwUquvyBZNJlPi+WcZ57ASRTbMjIxqeFjdW49eHG/65ISB+/xqrN5PtJKjzCRq/2I6omYWh7E5VIY2WpxL+FeQoYWNnvQw9GfXppEg95acDLaUjAmOaxkUzpPlXEqS4o2n7uG/JO4PeMS5S+cdaKKYchtEFT/ie+7TOpnoKOlSRtQeL3OZ0g3zVOXAaQRQ2HsNPh7fqSh4UNH7RHtPgF3H84aBa5fghsJQTH8CrRN4/OWC9/HbfdDN5Ru3pCmC+tNvFRKxZyc8xkxNv618rxU5pzY48nzKnTcrBudOr4b9fReZV3dW/nuUXNgWU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
