travis:
  secure:
    BINSTAR_TOKEN: baI1YaDpajV51f4fn7j8nerNhbWjgoil+bs/clPkUwKo5/2BMydHJLPGkegElN2oxAWy2NtZ2dS4Cgp6uVocyroPPIs8BEBmoCzhsnigSlrf1m/pqtFH29w5ZbRZatQJL0YO9QpQ39z9+dP6wCDgWkbA1U/oGcgy73S8UdkFj8+ygPuSnFbr/Q6I/MbvXE5Exta7SMTDQLQ5pkSR2Kn5sek4WVqMbsDyhJPkgrxVaMFCcN6Di2xjG5CINTgzhJeOuc+XjdPLo1bOGBj5cfFIKMkPWqG/aUbjFgD/i5VxYh+dAy97uXcO2NtnNnATABTnTDOLGLCyo2MKJv0010iCE4HowyLGOs8RSxZkhqGklZPvTlRdmskSG4QABCm2A88DpqInvXlFl1WqHViEQDgIXvV7dhUhgQdaQNaS33lir4MeFf3leMEJFAkuBJLv3cmqWy/KhJXaiv0oW/WeIbygWvgMEUB+kZOxfUIOpTwdYqfOw8W81b4fvsg/6alFSJpODAX6T0+muMeb4pEiwn4QfcLyF7KarP9xXj52oictpFi07Sscy6gPIDm8PH57qbOsijSAyf17Grn+ot/lnxYsx6ONLdaiK57wF2kPkFpPeuFoqSm24vugG4Q4zSZwweEiiU38s1zTM9+YElToW+7ovJb9XMFf68fChIPoXyjqd08=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
